### ISSUE TITLE
Add 1 paragraph overview of openfeature to README

### ISSUE THREAD

**Issue by lpil** [horvathandris/openfeature-gleam-sdk#28]
Hello!

The code looks cool, but I can't work out what this library is! It would be fab if the README started with a 1 paragraph overview of what openfeature is, possibly with a link to more information.

Thanks,
Louis

**Comment by horvathandris** [comment]
Hi Louis,
Thanks for taking a look, really appreciate it! 🙇🏻‍♂️  Updated the repo docs, hope it's a bit more clear now.
